
kan_url_root: https://bera.kanbanize.com/index.php/api/kanbanize/
kan_api_auth: login/
kan_api_projects_and_boards: get_projects_and_boards/
kan_api_get_task_details: get_task_details/

#
env_var_kan_api_key_name: KAN_API_KEY