
# key: hook, value: source file name

## pre-commit hook
# pre-commit: pre-commit.rb
pre-commit: pre-commit.filescan.sh

## commit-msg hook
# commit-msg: commit-msg.kanbanize.rb
# commit-msg.config: commit-msg.config

## pre-push hook
pre-push: pre-push.rb

